// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: go_side.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 用消息0
type Protocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{0}
}

func (x *Protocol) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Protocol) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ScProtocolPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pack []*Protocol `protobuf:"bytes,2,rep,name=pack,proto3" json:"pack,omitempty"`
}

func (x *ScProtocolPack) Reset() {
	*x = ScProtocolPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScProtocolPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScProtocolPack) ProtoMessage() {}

func (x *ScProtocolPack) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScProtocolPack.ProtoReflect.Descriptor instead.
func (*ScProtocolPack) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{1}
}

func (x *ScProtocolPack) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScProtocolPack) GetPack() []*Protocol {
	if x != nil {
		return x.Pack
	}
	return nil
}

// 进入房间
type CsEnterRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Room   string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`   // 房间类型eg: classic_ddz
	Place  string `protobuf:"bytes,3,opt,name=place,proto3" json:"place,omitempty"` // 场次 eg:normal
}

func (x *CsEnterRoom) Reset() {
	*x = CsEnterRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsEnterRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsEnterRoom) ProtoMessage() {}

func (x *CsEnterRoom) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsEnterRoom.ProtoReflect.Descriptor instead.
func (*CsEnterRoom) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{2}
}

func (x *CsEnterRoom) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *CsEnterRoom) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CsEnterRoom) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

// 登录1
type CsLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Verify   string `protobuf:"bytes,3,opt,name=verify,proto3" json:"verify,omitempty"`
	Device   string `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Ver      string `protobuf:"bytes,5,opt,name=ver,proto3" json:"ver,omitempty"`
	Channel  string `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"` // 渠道
}

func (x *CsLogin) Reset() {
	*x = CsLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsLogin) ProtoMessage() {}

func (x *CsLogin) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsLogin.ProtoReflect.Descriptor instead.
func (*CsLogin) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{3}
}

func (x *CsLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CsLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CsLogin) GetVerify() string {
	if x != nil {
		return x.Verify
	}
	return ""
}

func (x *CsLogin) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CsLogin) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *CsLogin) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// 注册2
type CsRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Cellphone string `protobuf:"bytes,3,opt,name=cellphone,proto3" json:"cellphone,omitempty"` // 手机
	Verify    string `protobuf:"bytes,4,opt,name=verify,proto3" json:"verify,omitempty"`       // 验证信息
	Device    string `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`       //设备号
	Ver       string `protobuf:"bytes,7,opt,name=ver,proto3" json:"ver,omitempty"`             //版本
	Local     string `protobuf:"bytes,8,opt,name=local,proto3" json:"local,omitempty"`         // 地区
	Channel   string `protobuf:"bytes,9,opt,name=channel,proto3" json:"channel,omitempty"`     // 渠道
}

func (x *CsRegister) Reset() {
	*x = CsRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsRegister) ProtoMessage() {}

func (x *CsRegister) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsRegister.ProtoReflect.Descriptor instead.
func (*CsRegister) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{4}
}

func (x *CsRegister) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CsRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CsRegister) GetCellphone() string {
	if x != nil {
		return x.Cellphone
	}
	return ""
}

func (x *CsRegister) GetVerify() string {
	if x != nil {
		return x.Verify
	}
	return ""
}

func (x *CsRegister) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CsRegister) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *CsRegister) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *CsRegister) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ScRegisterSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScRegisterSuccess) Reset() {
	*x = ScRegisterSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScRegisterSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScRegisterSuccess) ProtoMessage() {}

func (x *ScRegisterSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScRegisterSuccess.ProtoReflect.Descriptor instead.
func (*ScRegisterSuccess) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{5}
}

// 登录数据
type ScLoginSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player   string `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"` // 用户数据
	Id       int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Uuid     string `protobuf:"bytes,3,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	NickName string `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=Password,proto3" json:"Password,omitempty"`
	Gold     int64  `protobuf:"varint,7,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Coin     int64  `protobuf:"varint,8,opt,name=Coin,proto3" json:"Coin,omitempty"`
	RoomCard int64  `protobuf:"varint,9,opt,name=RoomCard,proto3" json:"RoomCard,omitempty"`
	Sex      int32  `protobuf:"varint,10,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Ver      string `protobuf:"bytes,11,opt,name=Ver,proto3" json:"Ver,omitempty"`
	Exp      int64  `protobuf:"varint,12,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Channel  string `protobuf:"bytes,13,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Phone    string `protobuf:"bytes,14,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email    string `protobuf:"bytes,15,opt,name=Email,proto3" json:"Email,omitempty"`
	Token    string `protobuf:"bytes,16,opt,name=Token,proto3" json:"Token,omitempty"`
	Head     string `protobuf:"bytes,17,opt,name=Head,proto3" json:"Head,omitempty"`
	Time     int64  `protobuf:"varint,18,opt,name=Time,proto3" json:"Time,omitempty"` // 时间戳
	UnionId  int64  `protobuf:"varint,19,opt,name=UnionId,proto3" json:"UnionId,omitempty"`
}

func (x *ScLoginSuccess) Reset() {
	*x = ScLoginSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScLoginSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScLoginSuccess) ProtoMessage() {}

func (x *ScLoginSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScLoginSuccess.ProtoReflect.Descriptor instead.
func (*ScLoginSuccess) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{6}
}

func (x *ScLoginSuccess) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *ScLoginSuccess) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScLoginSuccess) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ScLoginSuccess) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *ScLoginSuccess) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScLoginSuccess) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ScLoginSuccess) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *ScLoginSuccess) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *ScLoginSuccess) GetRoomCard() int64 {
	if x != nil {
		return x.RoomCard
	}
	return 0
}

func (x *ScLoginSuccess) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *ScLoginSuccess) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *ScLoginSuccess) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *ScLoginSuccess) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ScLoginSuccess) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ScLoginSuccess) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ScLoginSuccess) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ScLoginSuccess) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *ScLoginSuccess) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ScLoginSuccess) GetUnionId() int64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

type ScServers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServer string `protobuf:"bytes,1,opt,name=GameServer,proto3" json:"GameServer,omitempty"`
	ApiServer  string `protobuf:"bytes,2,opt,name=ApiServer,proto3" json:"ApiServer,omitempty"`
}

func (x *ScServers) Reset() {
	*x = ScServers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScServers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScServers) ProtoMessage() {}

func (x *ScServers) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScServers.ProtoReflect.Descriptor instead.
func (*ScServers) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{7}
}

func (x *ScServers) GetGameServer() string {
	if x != nil {
		return x.GameServer
	}
	return ""
}

func (x *ScServers) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

// 操作错误
type ScError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`    // code=-1 失败
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` //失败原因
}

func (x *ScError) Reset() {
	*x = ScError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScError) ProtoMessage() {}

func (x *ScError) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScError.ProtoReflect.Descriptor instead.
func (*ScError) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{8}
}

func (x *ScError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ScError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Prop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid       int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`             // 道具ID
	Size      int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`           // 数量
	LimitTime int64 `protobuf:"varint,4,opt,name=limitTime,proto3" json:"limitTime,omitempty"` // 期限
}

func (x *Prop) Reset() {
	*x = Prop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prop) ProtoMessage() {}

func (x *Prop) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prop.ProtoReflect.Descriptor instead.
func (*Prop) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{9}
}

func (x *Prop) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Prop) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Prop) GetLimitTime() int64 {
	if x != nil {
		return x.LimitTime
	}
	return 0
}

type ScPropList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pack []*Prop `protobuf:"bytes,1,rep,name=pack,proto3" json:"pack,omitempty"`
}

func (x *ScPropList) Reset() {
	*x = ScPropList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScPropList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScPropList) ProtoMessage() {}

func (x *ScPropList) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScPropList.ProtoReflect.Descriptor instead.
func (*ScPropList) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{10}
}

func (x *ScPropList) GetPack() []*Prop {
	if x != nil {
		return x.Pack
	}
	return nil
}

// 公告列表
type ScNoticeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pack []*ScNotice `protobuf:"bytes,1,rep,name=pack,proto3" json:"pack,omitempty"`
}

func (x *ScNoticeList) Reset() {
	*x = ScNoticeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScNoticeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScNoticeList) ProtoMessage() {}

func (x *ScNoticeList) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScNoticeList.ProtoReflect.Descriptor instead.
func (*ScNoticeList) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{11}
}

func (x *ScNoticeList) GetPack() []*ScNotice {
	if x != nil {
		return x.Pack
	}
	return nil
}

// 公告
type ScNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ScNotice) Reset() {
	*x = ScNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScNotice) ProtoMessage() {}

func (x *ScNotice) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScNotice.ProtoReflect.Descriptor instead.
func (*ScNotice) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{12}
}

func (x *ScNotice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScNotice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 活动列表
type ScActivitiesList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pack []*ScActivity `protobuf:"bytes,1,rep,name=pack,proto3" json:"pack,omitempty"`
}

func (x *ScActivitiesList) Reset() {
	*x = ScActivitiesList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScActivitiesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScActivitiesList) ProtoMessage() {}

func (x *ScActivitiesList) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScActivitiesList.ProtoReflect.Descriptor instead.
func (*ScActivitiesList) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{13}
}

func (x *ScActivitiesList) GetPack() []*ScActivity {
	if x != nil {
		return x.Pack
	}
	return nil
}

// 活动
type ScActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Img     string `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	Time    string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ScActivity) Reset() {
	*x = ScActivity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScActivity) ProtoMessage() {}

func (x *ScActivity) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScActivity.ProtoReflect.Descriptor instead.
func (*ScActivity) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{14}
}

func (x *ScActivity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScActivity) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScActivity) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *ScActivity) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type CsGameAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //see protocol.lua
	Reply  uint32  `protobuf:"varint,2,opt,name=reply,proto3" json:"reply,omitempty"`
	Pokers []int32 `protobuf:"varint,3,rep,packed,name=pokers,proto3" json:"pokers,omitempty"` //牌
}

func (x *CsGameAction) Reset() {
	*x = CsGameAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsGameAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsGameAction) ProtoMessage() {}

func (x *CsGameAction) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsGameAction.ProtoReflect.Descriptor instead.
func (*CsGameAction) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{15}
}

func (x *CsGameAction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CsGameAction) GetReply() uint32 {
	if x != nil {
		return x.Reply
	}
	return 0
}

func (x *CsGameAction) GetPokers() []int32 {
	if x != nil {
		return x.Pokers
	}
	return nil
}

// 心跳消息
type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{16}
}

type CsCreateUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Des  string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"` // 宣言
	Max  string `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"` // 人数上限
}

func (x *CsCreateUnion) Reset() {
	*x = CsCreateUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsCreateUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCreateUnion) ProtoMessage() {}

func (x *CsCreateUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCreateUnion.ProtoReflect.Descriptor instead.
func (*CsCreateUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{17}
}

func (x *CsCreateUnion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CsCreateUnion) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *CsCreateUnion) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

type ScCreateUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string       `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Info   *ScUnionInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ScCreateUnion) Reset() {
	*x = ScCreateUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScCreateUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScCreateUnion) ProtoMessage() {}

func (x *ScCreateUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScCreateUnion.ProtoReflect.Descriptor instead.
func (*ScCreateUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{18}
}

func (x *ScCreateUnion) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ScCreateUnion) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ScCreateUnion) GetInfo() *ScUnionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CsJoinUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId int32 `protobuf:"varint,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
}

func (x *CsJoinUnion) Reset() {
	*x = CsJoinUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsJoinUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsJoinUnion) ProtoMessage() {}

func (x *CsJoinUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsJoinUnion.ProtoReflect.Descriptor instead.
func (*CsJoinUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{19}
}

func (x *CsJoinUnion) GetUnionId() int32 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

type ScJoinUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string       `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Info   *ScUnionInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ScJoinUnion) Reset() {
	*x = ScJoinUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScJoinUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScJoinUnion) ProtoMessage() {}

func (x *ScJoinUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScJoinUnion.ProtoReflect.Descriptor instead.
func (*ScJoinUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{20}
}

func (x *ScJoinUnion) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ScJoinUnion) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ScJoinUnion) GetInfo() *ScUnionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CsQueryUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CsQueryUnion) Reset() {
	*x = CsQueryUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsQueryUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsQueryUnion) ProtoMessage() {}

func (x *CsQueryUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsQueryUnion.ProtoReflect.Descriptor instead.
func (*CsQueryUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{21}
}

func (x *CsQueryUnion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CsUnionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId int64 `protobuf:"varint,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
}

func (x *CsUnionInfo) Reset() {
	*x = CsUnionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsUnionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsUnionInfo) ProtoMessage() {}

func (x *CsUnionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsUnionInfo.ProtoReflect.Descriptor instead.
func (*CsUnionInfo) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{22}
}

func (x *CsUnionInfo) GetUnionId() int64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

type ScUnionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32            `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Notice        string           `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	Des           string           `protobuf:"bytes,5,opt,name=des,proto3" json:"des,omitempty"`
	Score         int64            `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	MasterId      int64            `protobuf:"varint,7,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Creator       string           `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime    int64            `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MaxMember     int32            `protobuf:"varint,10,opt,name=max_member,json=maxMember,proto3" json:"max_member,omitempty"`
	Status        int32            `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Rank          int32            `protobuf:"varint,12,opt,name=rank,proto3" json:"rank,omitempty"`
	Members       []*ScUnionMember `protobuf:"bytes,13,rep,name=members,proto3" json:"members,omitempty"`
	CurrentMember int32            `protobuf:"varint,14,opt,name=current_member,json=currentMember,proto3" json:"current_member,omitempty"`
	MasterUuid    string           `protobuf:"bytes,15,opt,name=master_uuid,json=masterUuid,proto3" json:"master_uuid,omitempty"`
}

func (x *ScUnionInfo) Reset() {
	*x = ScUnionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScUnionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScUnionInfo) ProtoMessage() {}

func (x *ScUnionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScUnionInfo.ProtoReflect.Descriptor instead.
func (*ScUnionInfo) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{23}
}

func (x *ScUnionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScUnionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScUnionInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ScUnionInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *ScUnionInfo) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *ScUnionInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScUnionInfo) GetMasterId() int64 {
	if x != nil {
		return x.MasterId
	}
	return 0
}

func (x *ScUnionInfo) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *ScUnionInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ScUnionInfo) GetMaxMember() int32 {
	if x != nil {
		return x.MaxMember
	}
	return 0
}

func (x *ScUnionInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ScUnionInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ScUnionInfo) GetMembers() []*ScUnionMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ScUnionInfo) GetCurrentMember() int32 {
	if x != nil {
		return x.CurrentMember
	}
	return 0
}

func (x *ScUnionInfo) GetMasterUuid() string {
	if x != nil {
		return x.MasterUuid
	}
	return ""
}

type ScQueryUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unions []*ScUnionInfo `protobuf:"bytes,1,rep,name=unions,proto3" json:"unions,omitempty"`
}

func (x *ScQueryUnion) Reset() {
	*x = ScQueryUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScQueryUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScQueryUnion) ProtoMessage() {}

func (x *ScQueryUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScQueryUnion.ProtoReflect.Descriptor instead.
func (*ScQueryUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{24}
}

func (x *ScQueryUnion) GetUnions() []*ScUnionInfo {
	if x != nil {
		return x.Unions
	}
	return nil
}

// 获取邮件
type CsMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsMailReq) Reset() {
	*x = CsMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsMailReq) ProtoMessage() {}

func (x *CsMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsMailReq.ProtoReflect.Descriptor instead.
func (*CsMailReq) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{25}
}

// 读取邮件
type CsReadMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId  int64 `protobuf:"varint,1,opt,name=mailId,proto3" json:"mailId,omitempty"`
	Confirm bool  `protobuf:"varint,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
}

func (x *CsReadMail) Reset() {
	*x = CsReadMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsReadMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsReadMail) ProtoMessage() {}

func (x *CsReadMail) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsReadMail.ProtoReflect.Descriptor instead.
func (*CsReadMail) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{26}
}

func (x *CsReadMail) GetMailId() int64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *CsReadMail) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

// 邮件列表
type ScMails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails []*Mail `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails,omitempty"`
}

func (x *ScMails) Reset() {
	*x = ScMails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScMails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScMails) ProtoMessage() {}

func (x *ScMails) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScMails.ProtoReflect.Descriptor instead.
func (*ScMails) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{27}
}

func (x *ScMails) GetMails() []*Mail {
	if x != nil {
		return x.Mails
	}
	return nil
}

// 邮件
type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Sender   string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Title    string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content  string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Attach   string `protobuf:"bytes,7,opt,name=attach,proto3" json:"attach,omitempty"`
	Read     bool   `protobuf:"varint,8,opt,name=read,proto3" json:"read,omitempty"`
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{28}
}

func (x *Mail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mail) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Mail) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Mail) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Mail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Mail) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *Mail) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

// 公会成员
type ScUnionMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level      int64  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	UnionVal   int64  `protobuf:"varint,3,opt,name=unionVal,proto3" json:"unionVal,omitempty"` // 贡献值
	Head       string `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	PlayerUuid string `protobuf:"bytes,5,opt,name=playerUuid,proto3" json:"playerUuid,omitempty"`
}

func (x *ScUnionMember) Reset() {
	*x = ScUnionMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScUnionMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScUnionMember) ProtoMessage() {}

func (x *ScUnionMember) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScUnionMember.ProtoReflect.Descriptor instead.
func (*ScUnionMember) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{29}
}

func (x *ScUnionMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScUnionMember) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ScUnionMember) GetUnionVal() int64 {
	if x != nil {
		return x.UnionVal
	}
	return 0
}

func (x *ScUnionMember) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *ScUnionMember) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

type CsExitUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId int64 `protobuf:"varint,1,opt,name=unionId,proto3" json:"unionId,omitempty"`
}

func (x *CsExitUnion) Reset() {
	*x = CsExitUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsExitUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsExitUnion) ProtoMessage() {}

func (x *CsExitUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsExitUnion.ProtoReflect.Descriptor instead.
func (*CsExitUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{30}
}

func (x *CsExitUnion) GetUnionId() int64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

type ScExitUnion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *ScExitUnion) Reset() {
	*x = ScExitUnion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScExitUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScExitUnion) ProtoMessage() {}

func (x *ScExitUnion) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScExitUnion.ProtoReflect.Descriptor instead.
func (*ScExitUnion) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{31}
}

func (x *ScExitUnion) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ScExitUnion) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

// 公会设置
type CsUnionSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notice string `protobuf:"bytes,1,opt,name=notice,proto3" json:"notice,omitempty"`  // 公告
	Des    string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`        // 描述
	Verify int32  `protobuf:"varint,3,opt,name=verify,proto3" json:"verify,omitempty"` // 验证级别 //0=open// 1= 验证 // 2= 拒绝
}

func (x *CsUnionSettings) Reset() {
	*x = CsUnionSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsUnionSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsUnionSettings) ProtoMessage() {}

func (x *CsUnionSettings) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsUnionSettings.ProtoReflect.Descriptor instead.
func (*CsUnionSettings) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{32}
}

func (x *CsUnionSettings) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *CsUnionSettings) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *CsUnionSettings) GetVerify() int32 {
	if x != nil {
		return x.Verify
	}
	return 0
}

// 转让管理员
type CsTransferMaster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CsTransferMaster) Reset() {
	*x = CsTransferMaster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsTransferMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsTransferMaster) ProtoMessage() {}

func (x *CsTransferMaster) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsTransferMaster.ProtoReflect.Descriptor instead.
func (*CsTransferMaster) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{33}
}

func (x *CsTransferMaster) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ScTransferMaster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ScTransferMaster) Reset() {
	*x = ScTransferMaster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScTransferMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScTransferMaster) ProtoMessage() {}

func (x *ScTransferMaster) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScTransferMaster.ProtoReflect.Descriptor instead.
func (*ScTransferMaster) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{34}
}

func (x *ScTransferMaster) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 踢出成员
type CsTickMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CsTickMember) Reset() {
	*x = CsTickMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsTickMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsTickMember) ProtoMessage() {}

func (x *CsTickMember) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsTickMember.ProtoReflect.Descriptor instead.
func (*CsTickMember) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{35}
}

func (x *CsTickMember) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ScTickMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ScTickMember) Reset() {
	*x = ScTickMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScTickMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScTickMember) ProtoMessage() {}

func (x *ScTickMember) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScTickMember.ProtoReflect.Descriptor instead.
func (*ScTickMember) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{36}
}

func (x *ScTickMember) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 公会排行榜
type CsUnionRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsUnionRank) Reset() {
	*x = CsUnionRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsUnionRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsUnionRank) ProtoMessage() {}

func (x *CsUnionRank) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsUnionRank.ProtoReflect.Descriptor instead.
func (*CsUnionRank) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{37}
}

type ScUnionRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unions []*ScUnionInfo `protobuf:"bytes,1,rep,name=unions,proto3" json:"unions,omitempty"`
}

func (x *ScUnionRank) Reset() {
	*x = ScUnionRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScUnionRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScUnionRank) ProtoMessage() {}

func (x *ScUnionRank) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScUnionRank.ProtoReflect.Descriptor instead.
func (*ScUnionRank) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{38}
}

func (x *ScUnionRank) GetUnions() []*ScUnionInfo {
	if x != nil {
		return x.Unions
	}
	return nil
}

// 位置信息
type CsLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *CsLocation) Reset() {
	*x = CsLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsLocation) ProtoMessage() {}

func (x *CsLocation) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsLocation.ProtoReflect.Descriptor instead.
func (*CsLocation) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{39}
}

func (x *CsLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ScLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *ScLocation) Reset() {
	*x = ScLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_side_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScLocation) ProtoMessage() {}

func (x *ScLocation) ProtoReflect() protoreflect.Message {
	mi := &file_go_side_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScLocation.ProtoReflect.Descriptor instead.
func (*ScLocation) Descriptor() ([]byte, []int) {
	return file_go_side_proto_rawDescGZIP(), []int{40}
}

func (x *ScLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_go_side_proto protoreflect.FileDescriptor

var file_go_side_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x6f, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x34, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x10, 0x73, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x70, 0x61, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x52, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x22, 0x4f, 0x0a, 0x0b, 0x43, 0x73, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x43, 0x73,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0xd4, 0x01, 0x0a, 0x0a, 0x43, 0x73,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x22, 0x13, 0x0a, 0x11, 0x53, 0x63, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xb0, 0x03, 0x0a, 0x0e, 0x53, 0x63, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x47, 0x6f, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x43, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x65, 0x72, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x78, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x18, 0x11,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x09, 0x53, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x07, 0x53, 0x63, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x04, 0x50, 0x72,
	0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0a, 0x53, 0x63, 0x50, 0x72, 0x6f, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x22,
	0x2d, 0x0a, 0x0c, 0x53, 0x63, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x53, 0x63, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x22, 0x3a,
	0x0a, 0x08, 0x53, 0x63, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x10, 0x53, 0x63,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53,
	0x63, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x04, 0x70, 0x61, 0x63, 0x6b, 0x22,
	0x62, 0x0a, 0x0a, 0x53, 0x63, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x63, 0x73, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x6b,
	0x65, 0x72, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x22, 0x47, 0x0a, 0x0d, 0x43, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x59, 0x0a, 0x0d, 0x53, 0x63, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x53, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x73, 0x4a, 0x6f, 0x69, 0x6e, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x57, 0x0a,
	0x0b, 0x53, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x73, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x73,
	0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x9c, 0x03, 0x0a, 0x0b, 0x53, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x22, 0x34, 0x0a, 0x0c, 0x53, 0x63, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x6e, 0x69,
	0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x73, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x73, 0x52, 0x65, 0x61, 0x64, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x26, 0x0a, 0x07, 0x53, 0x63, 0x4d, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x1b, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xba, 0x01,
	0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x53,
	0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x56,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x56,
	0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0b, 0x43, 0x73, 0x45, 0x78, 0x69, 0x74,
	0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x2f, 0x0a, 0x0b, 0x53, 0x63, 0x45, 0x78, 0x69, 0x74, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73,
	0x22, 0x53, 0x0a, 0x0f, 0x43, 0x73, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x26, 0x0a,
	0x10, 0x53, 0x63, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x73, 0x54, 0x69, 0x63, 0x6b, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x63, 0x54,
	0x69, 0x63, 0x6b, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x0d, 0x0a,
	0x0b, 0x43, 0x73, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x33, 0x0a, 0x0b,
	0x53, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x06, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x63,
	0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x28, 0x0a, 0x0a, 0x43, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x0a, 0x53,
	0x63, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_side_proto_rawDescOnce sync.Once
	file_go_side_proto_rawDescData = file_go_side_proto_rawDesc
)

func file_go_side_proto_rawDescGZIP() []byte {
	file_go_side_proto_rawDescOnce.Do(func() {
		file_go_side_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_side_proto_rawDescData)
	})
	return file_go_side_proto_rawDescData
}

var file_go_side_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_go_side_proto_goTypes = []interface{}{
	(*Protocol)(nil),          // 0: protocol
	(*ScProtocolPack)(nil),    // 1: sc_protocol_pack
	(*CsEnterRoom)(nil),       // 2: CsEnterRoom
	(*CsLogin)(nil),           // 3: CsLogin
	(*CsRegister)(nil),        // 4: CsRegister
	(*ScRegisterSuccess)(nil), // 5: ScRegisterSuccess
	(*ScLoginSuccess)(nil),    // 6: ScLoginSuccess
	(*ScServers)(nil),         // 7: ScServers
	(*ScError)(nil),           // 8: ScError
	(*Prop)(nil),              // 9: Prop
	(*ScPropList)(nil),        // 10: ScPropList
	(*ScNoticeList)(nil),      // 11: ScNoticeList
	(*ScNotice)(nil),          // 12: ScNotice
	(*ScActivitiesList)(nil),  // 13: ScActivitiesList
	(*ScActivity)(nil),        // 14: ScActivity
	(*CsGameAction)(nil),      // 15: cs_game_action
	(*Heartbeat)(nil),         // 16: heartbeat
	(*CsCreateUnion)(nil),     // 17: CsCreateUnion
	(*ScCreateUnion)(nil),     // 18: ScCreateUnion
	(*CsJoinUnion)(nil),       // 19: CsJoinUnion
	(*ScJoinUnion)(nil),       // 20: ScJoinUnion
	(*CsQueryUnion)(nil),      // 21: CsQueryUnion
	(*CsUnionInfo)(nil),       // 22: CsUnionInfo
	(*ScUnionInfo)(nil),       // 23: ScUnionInfo
	(*ScQueryUnion)(nil),      // 24: ScQueryUnion
	(*CsMailReq)(nil),         // 25: CsMailReq
	(*CsReadMail)(nil),        // 26: CsReadMail
	(*ScMails)(nil),           // 27: ScMails
	(*Mail)(nil),              // 28: Mail
	(*ScUnionMember)(nil),     // 29: ScUnionMember
	(*CsExitUnion)(nil),       // 30: CsExitUnion
	(*ScExitUnion)(nil),       // 31: ScExitUnion
	(*CsUnionSettings)(nil),   // 32: CsUnionSettings
	(*CsTransferMaster)(nil),  // 33: CsTransferMaster
	(*ScTransferMaster)(nil),  // 34: ScTransferMaster
	(*CsTickMember)(nil),      // 35: CsTickMember
	(*ScTickMember)(nil),      // 36: ScTickMember
	(*CsUnionRank)(nil),       // 37: CsUnionRank
	(*ScUnionRank)(nil),       // 38: ScUnionRank
	(*CsLocation)(nil),        // 39: CsLocation
	(*ScLocation)(nil),        // 40: ScLocation
}
var file_go_side_proto_depIdxs = []int32{
	0,  // 0: sc_protocol_pack.pack:type_name -> protocol
	9,  // 1: ScPropList.pack:type_name -> Prop
	12, // 2: ScNoticeList.pack:type_name -> ScNotice
	14, // 3: ScActivitiesList.pack:type_name -> ScActivity
	23, // 4: ScCreateUnion.info:type_name -> ScUnionInfo
	23, // 5: ScJoinUnion.info:type_name -> ScUnionInfo
	29, // 6: ScUnionInfo.members:type_name -> ScUnionMember
	23, // 7: ScQueryUnion.unions:type_name -> ScUnionInfo
	28, // 8: ScMails.mails:type_name -> Mail
	23, // 9: ScUnionRank.unions:type_name -> ScUnionInfo
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_go_side_proto_init() }
func file_go_side_proto_init() {
	if File_go_side_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_side_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Protocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScProtocolPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsEnterRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScRegisterSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScLoginSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScServers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScPropList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScNoticeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScActivitiesList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScActivity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsGameAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsCreateUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScCreateUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsJoinUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScJoinUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsQueryUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsUnionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScUnionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScQueryUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsReadMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScMails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScUnionMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsExitUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScExitUnion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsUnionSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsTransferMaster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScTransferMaster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsTickMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScTickMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsUnionRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScUnionRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_side_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_side_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_side_proto_goTypes,
		DependencyIndexes: file_go_side_proto_depIdxs,
		MessageInfos:      file_go_side_proto_msgTypes,
	}.Build()
	File_go_side_proto = out.File
	file_go_side_proto_rawDesc = nil
	file_go_side_proto_goTypes = nil
	file_go_side_proto_depIdxs = nil
}
