---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/22 18:17
---

function room_init(pid,rid)
    rooms[pid] = rid
    for key, value in pairs(rooms) do
        print(key,value)
    end
    print("init room ", pid)
end

function player_init(pid,playerdata)
    print("init player ", pid)
    print(playerdata)
    return true
end

function enter_room(pid)
    print("player ", pid," enter room")
    -- A register room id
<<<<<<< .mine
    return "1514ba25-e773-44ec-b916-c4ea4b0ebf9e"
||||||| .r125
    return "4ddb5ffd-0bd4-4ad7-b860-a53d3b321747"
=======
    return "0cc94e5f-4bac-459f-8150-5aea66dfe334"
>>>>>>> .r128
end

function onmessage(m,x)
    hotupdate()
    print("on::",m,x)
    msgs = msgs + 1
    for key, value in pairs(rooms) do
        print(key,value)
    end
    return msgs
end

function hotupdate()
    --print(hello)
    print("ok hot 888  ...")
end
